#!/bin/sh -e
# Automatically added by dh_dkms -  but overwritten by Librealsense to enforce reloading
#of the modified kernel modules without restarting the PC.
#Note for maintainer - In order to generate the basic skeleton of this file one needs to
# completely remove/rename it from`debian` directory, then rebuild the package and
# so that this file will be regenerated.
#This will be required when the version of the package is promoted ( note the hard-coded
# automatically-generated value below: DKMS_VERSION=1.2.0
# The original file can be found in template-dkms-mkdeb/debian/postinst
# in the DKMS tarball, check it for copyright notices.

DKMS_NAME=librealsense2-dkms
DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
DKMS_VERSION=1.3.24

postinst_found=0

case "$1" in
	configure)
		for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
			if [ -f $DKMS_POSTINST ]; then
				$DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
				postinst_found=1
				break
			fi
		done
		if [ "$postinst_found" -eq 0 ]; then
			echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
			echo "built with legacy DKMS support."
			echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
			echo "support or upgrade DKMS to a more current version."
			exit 1
		fi
	;;
esac
# End automatically added section

#Load the newly-built modules into the kernel to make them immedeately available
# It will allow to skip the `restart` step in the installation guide
echo -n "\nLoading the modified modules into kernel..."
sudo modprobe -r uvcvideo && sudo modprobe -r videodev && \
sudo modprobe uvcvideo && echo " complete"
echo Current status:
dkms status
echo 'mod: videodev \t\t\t' ` modinfo videodev | grep ^version:`
echo 'mod: uvcvideo \t\t\t' `modinfo uvcvideo | grep ^version:`

